services:
  app:
    image: insider-assesment-app
    build: 
      context: app/
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - DATABASE_URL=postgres://devuser:devpassword@db:5432/devdb?sslmode=disable
      - REDIS_URL=redis://redis:6379
      - MESSAGE_SEND_INTERVAL=120 # 2 minutes 
      - MESSAGE_SEND_BATCH_SIZE=2 # 2 records
      - WEBHOOK_URL=http://webhook:8081/api/receive-message
      - WEBHOOK_AUTH_KEY=insider-auth-key-123
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  webhook:
    image: insider-assesment-webhook.site-simulator
    build: 
      context: webhook.site/
    ports:
      - 8081:8081
    environment:
      - PORT=8081
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    image: postgres:16.4-alpine
    environment:
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpassword
      - POSTGRES_DB=devdb
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d devdb -U devuser"]
      interval: 1s
      retries: 30

  redis:
    image: redis:7.4.0-alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    healthcheck:
       test: ["CMD", "redis-cli","ping"]
       interval: 1s
       retries: 30

volumes:
  postgres_data:
  redis_data:
