version: '3.8'

services:
  app:
    image: insider
    build: 
      context: .
    ports:
      - 8080:8080
    environment:
      - MODE=appserver
      - DATABASE_URL=postgres://devuser:devpassword@db:5432/devdb?sslmode=disable
      - REDIS_URL=redis://redis:6379
      - SERVER_PORT=8080
      - MESSAGE_SEND_INTERVAL=5 
      - MESSAGE_SEND_BATCH_SIZE=1
      - WEBHOOK_URL=http://webhook_test:8081/api/receive-message
      - WEBHOOK_AUTH_KEY=insider-auth-key-123
    depends_on:
    - db  
    - redis 

  webhook_test:
    image: insider
    build: 
      context: .
    ports:
      - 8081:8081
    environment:
      - MODE=webhookserver
      - LOCAL_WEBHOOK_SERVER_PORT=8081
    depends_on:
    - db  
    - redis 

  db:
    image: postgres:16.4-alpine
    environment:
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpassword
      - POSTGRES_DB=devdb
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.4.0-alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
