definitions:
  models.AddMessageRequest:
    properties:
      content:
        type: string
      recipient:
        type: string
    type: object
  models.AddMessageResponse:
    properties:
      content:
        type: string
      id:
        type: integer
      recipient:
        type: string
    type: object
  models.CreateMessageErrorResponse:
    properties:
      error:
        type: string
      message:
        type: string
    type: object
  models.MessageProcessingResponse:
    properties:
      message:
        type: string
    type: object
  models.SentMessageResponseModel:
    properties:
      content:
        type: string
      id:
        type: integer
      recipient:
        type: string
    type: object
info:
  contact: {}
paths:
  /messages:
    post:
      description: Create a new message with content and recipient.
      parameters:
      - description: Message request payload
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/models.AddMessageRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success response
          schema:
            $ref: '#/definitions/models.AddMessageResponse'
        "400":
          description: Bad request response
          schema:
            $ref: '#/definitions/models.CreateMessageErrorResponse'
      summary: Create a new message
      tags:
      - messages
  /messages/processing/start:
    post:
      description: Start the message sending job
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.MessageProcessingResponse'
      summary: Start message processing
      tags:
      - processing
  /messages/processing/stop:
    post:
      description: Stop the message sending job
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.MessageProcessingResponse'
      summary: Stop message processing
      tags:
      - processing
  /messages/sent:
    get:
      description: Retrieve all sent messages
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.SentMessageResponseModel'
            type: array
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get sent messages
      tags:
      - messages
swagger: "2.0"
