// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
	"time"
)

type Message struct {
	ID        int32
	Content   string
	Recipient string
	Tries     int16
	CreatedAt time.Time
	SendingAt sql.NullTime
	SentAt    sql.NullTime
}
